// Generated by gencpp from file chessbot_control/RG2_GripRequest.msg
// DO NOT EDIT!


#ifndef CHESSBOT_CONTROL_MESSAGE_RG2_GRIPREQUEST_H
#define CHESSBOT_CONTROL_MESSAGE_RG2_GRIPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chessbot_control
{
template <class ContainerAllocator>
struct RG2_GripRequest_
{
  typedef RG2_GripRequest_<ContainerAllocator> Type;

  RG2_GripRequest_()
    {
    }
  RG2_GripRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RG2_GripRequest_

typedef ::chessbot_control::RG2_GripRequest_<std::allocator<void> > RG2_GripRequest;

typedef boost::shared_ptr< ::chessbot_control::RG2_GripRequest > RG2_GripRequestPtr;
typedef boost::shared_ptr< ::chessbot_control::RG2_GripRequest const> RG2_GripRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chessbot_control::RG2_GripRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chessbot_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::chessbot_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chessbot_control/RG2_GripRequest";
  }

  static const char* value(const ::chessbot_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::chessbot_control::RG2_GripRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RG2_GripRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chessbot_control::RG2_GripRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::chessbot_control::RG2_GripRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CHESSBOT_CONTROL_MESSAGE_RG2_GRIPREQUEST_H
